# Generated by Django 4.0.3 on 2022-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_Name', models.CharField(max_length=20, verbose_name='菜品名称')),
                ('Dish_Heat', models.FloatField(verbose_name='热量')),
                ('Dish_Carbohydrate', models.FloatField(verbose_name='碳水化合物含量')),
                ('Dish_Protein', models.FloatField(verbose_name='蛋白质含量')),
                ('Dish_Fat', models.FloatField(verbose_name='脂肪含量')),
                ('Dish_Cholesterol', models.FloatField(verbose_name='胆固醇含量')),
                ('Dish_Mineral', models.FloatField(verbose_name='矿物质含量')),
                ('Dish_Carotene', models.FloatField(verbose_name='胡萝卜素含量')),
                ('Dish_Vitamin_A', models.FloatField(verbose_name='维生素A含量')),
                ('Dish_Vitamin_C', models.FloatField(verbose_name='维生素A含量')),
                ('Dish_Vitamin_E', models.FloatField(verbose_name='维生素A含量')),
                ('Dish_Vitamin_B1', models.FloatField(verbose_name='维生素A含量')),
                ('Dish_Vitamin_B2', models.FloatField(verbose_name='维生素A含量')),
                ('Dish_Dietary', models.FloatField(verbose_name='膳食纤维')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '菜品基本信息',
                'verbose_name_plural': '菜品基本信息',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sport_Name', models.CharField(max_length=20, verbose_name='运动名称')),
                ('Sport_Time', models.FloatField(blank=True, default=0, null=True, verbose_name='运动时间')),
                ('Sport_Times', models.IntegerField(blank=True, default=0, null=True, verbose_name='运动次数')),
                ('Sport_Distance', models.FloatField(blank=True, default=0, null=True, verbose_name='运动里程')),
                ('Sport_Consume', models.FloatField(blank=True, default=0, null=True, verbose_name='单位消耗')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '日常运动基本信息',
                'verbose_name_plural': '日常运动基本信息',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Id', models.CharField(max_length=100, unique=True, verbose_name='openid')),
                ('Nick_Name', models.CharField(max_length=50, null=True, unique=True, verbose_name='用户名')),
                ('User_Age', models.IntegerField(null=True, verbose_name='用户年龄')),
                ('User_Gender', models.CharField(max_length=10, null=True, verbose_name='用户性别')),
                ('User_Height', models.FloatField(null=True, verbose_name='身高')),
                ('User_Weight', models.FloatField(null=True, verbose_name='体重')),
                ('User_Borntime', models.DateTimeField(null=True, verbose_name='用户出生日期')),
                ('User_BMI', models.FloatField(null=True, verbose_name='BMI')),
                ('User_Bfp', models.FloatField(null=True, verbose_name='体脂率')),
                ('User_Metabolism', models.FloatField(null=True, verbose_name='每日基础代谢卡路里')),
                ('User_Consume', models.FloatField(default=0, null=True, verbose_name='每日待消耗热量')),
                ('User_Residualheat', models.FloatField(default=0, null=True, verbose_name='当天摄入的卡路里')),
                ('User_Contend', models.CharField(default='该用户很懒，还没有发表任何简介', max_length=100, null=True, verbose_name='个性标签')),
                ('User_Target', models.IntegerField(default=0, null=True, verbose_name='用户目的')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户的基本信息',
            },
        ),
        migrations.CreateModel(
            name='UserSportLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Id', models.CharField(max_length=100, null=True, verbose_name='openid')),
                ('Nick_Name', models.CharField(max_length=50, null=True, verbose_name='用户名')),
                ('SportLike_one', models.CharField(max_length=20, null=True, verbose_name='运动名称')),
                ('SportLike_two', models.CharField(max_length=20, null=True, verbose_name='运动名称')),
                ('SportLike_three', models.CharField(max_length=20, null=True, verbose_name='运动名称')),
                ('SportLike_four', models.CharField(max_length=20, null=True, verbose_name='运动名称')),
                ('SportLike_five', models.CharField(max_length=20, null=True, verbose_name='运动名称')),
                ('SportLike_six', models.CharField(max_length=20, null=True, verbose_name='运动名称')),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
