# Generated by Django 4.0.3 on 2022-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersportlike',
            options={'verbose_name': '用户感兴趣的运动信息', 'verbose_name_plural': '用户感兴趣的运动信息'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Carbohydrate',
            field=models.FloatField(null=True, verbose_name='碳水化合物含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Carotene',
            field=models.FloatField(null=True, verbose_name='胡萝卜素含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Cholesterol',
            field=models.FloatField(null=True, verbose_name='胆固醇含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Dietary',
            field=models.FloatField(null=True, verbose_name='膳食纤维'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Fat',
            field=models.FloatField(null=True, verbose_name='脂肪含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Mineral',
            field=models.FloatField(null=True, verbose_name='矿物质含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Protein',
            field=models.FloatField(null=True, verbose_name='蛋白质含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Vitamin_A',
            field=models.FloatField(null=True, verbose_name='维生素A含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Vitamin_B1',
            field=models.FloatField(null=True, verbose_name='维生素B1含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Vitamin_B2',
            field=models.FloatField(null=True, verbose_name='维生素B2含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Vitamin_C',
            field=models.FloatField(null=True, verbose_name='维生素C含量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Vitamin_E',
            field=models.FloatField(null=True, verbose_name='维生素E含量'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Nick_Name',
            field=models.CharField(max_length=50, null=True, verbose_name='用户名'),
        ),
    ]
