# Generated by Django 4.0.3 on 2022-04-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0002_alter_usersportlike_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Id', models.CharField(max_length=100, unique=True, verbose_name='openid')),
                ('Nick_Name', models.CharField(max_length=50, null=True, verbose_name='用户名')),
                ('User_Weight_One', models.FloatField(null=True, verbose_name='体重one')),
                ('User_Weight_Two', models.FloatField(null=True, verbose_name='体重two')),
                ('User_Weight_Three', models.FloatField(null=True, verbose_name='体重three')),
                ('User_Weight_Four', models.FloatField(null=True, verbose_name='体重four')),
                ('User_Weight_Five', models.FloatField(null=True, verbose_name='体重five')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户体重基本信息',
                'verbose_name_plural': '用户体重基本信息',
            },
        ),
    ]
