# Generated by Django 4.0.3 on 2022-04-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0003_weightinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Last_Time',
            field=models.CharField(max_length=100, null=True, verbose_name='最后一次登录时间'),
        ),
    ]
