# Generated by Django 4.0.3 on 2022-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0004_userinfo_last_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Last_Login',
            field=models.DateTimeField(null=True, verbose_name='最后一次登录时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Last_Time',
            field=models.CharField(max_length=100, null=True, verbose_name='测试'),
        ),
    ]
