# Generated by Django 4.0.3 on 2022-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0005_userinfo_last_login_alter_userinfo_last_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='User_Sport_Heat',
            field=models.FloatField(default=0, null=True, verbose_name='当天累计运动消耗卡路里'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='User_Sport_Time',
            field=models.FloatField(default=0, null=True, verbose_name='当天累计运动时长'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Last_Time',
            field=models.CharField(max_length=100, null=True, verbose_name='最后一次登录时间'),
        ),
    ]
