# Generated by Django 4.0.3 on 2022-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0006_userinfo_user_sport_heat_userinfo_user_sport_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_Cycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Id', models.CharField(max_length=100, unique=True, verbose_name='openid')),
                ('Sport_Name', models.CharField(default='骑单车', max_length=100, unique=True, verbose_name='运动名称')),
                ('Cycling_Time', models.FloatField(null=True, verbose_name='运动时长')),
                ('Cycling_Calorie', models.FloatField(null=True, verbose_name='运动累计消耗')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '骑单车信息表',
                'verbose_name_plural': '骑单车信息表',
            },
        ),
        migrations.CreateModel(
            name='Sport_Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Id', models.CharField(max_length=100, unique=True, verbose_name='openid')),
                ('Sport_Name', models.CharField(default='跑步', max_length=100, unique=True, verbose_name='运动名称')),
                ('Run_Time', models.FloatField(null=True, verbose_name='运动时长')),
                ('Run_Calorie', models.FloatField(null=True, verbose_name='运动累计消耗')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '跑步信息表',
                'verbose_name_plural': '跑步信息表',
            },
        ),
        migrations.CreateModel(
            name='Sport_Swim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Id', models.CharField(max_length=100, unique=True, verbose_name='openid')),
                ('Sport_Name', models.CharField(default='游泳', max_length=100, unique=True, verbose_name='运动名称')),
                ('Swim_Time', models.FloatField(null=True, verbose_name='运动时长')),
                ('Swim_Calorie', models.FloatField(null=True, verbose_name='运动累计消耗')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '游泳信息表',
                'verbose_name_plural': '游泳信息表',
            },
        ),
    ]
