# Generated by Django 4.0.3 on 2022-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0007_sport_cycling_sport_run_sport_swim'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Open_Id', models.CharField(max_length=100, unique=True, verbose_name='openid')),
                ('Feed_Name', models.CharField(max_length=200, null=True, unique=True, verbose_name='反馈与建议')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '反馈与建议信息表',
                'verbose_name_plural': '反馈与建议信息表',
            },
        ),
        migrations.AddField(
            model_name='sport_cycling',
            name='Sport_Mark',
            field=models.IntegerField(default=0, unique=True, verbose_name='运动标记'),
        ),
        migrations.AddField(
            model_name='sport_run',
            name='Sport_Mark',
            field=models.IntegerField(default=0, unique=True, verbose_name='运动标记'),
        ),
        migrations.AddField(
            model_name='sport_swim',
            name='Sport_Mark',
            field=models.IntegerField(default=0, unique=True, verbose_name='运动标记'),
        ),
    ]
